version: "2"

linters:
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - (*github.com/fatih/color.Color).Fprint
        - (*github.com/fatih/color.Color).Fprintf
        - (*github.com/fatih/color.Color).Fprintln
